07_RelationalOperator:07_RelationalOperator.c 
	gcc -c 07_RelationalOperator.c 
	gcc 07_RelationalOperator.o -o 07_RelationalOperator

run:
	@./07_RelationalOperator

clean:
	rm -rf 07_RelationalOperator 07_RelationalOperator.o 