04_ConditionalOperator:04_ConditionalOperator.c
	gcc -c 04_ConditionalOperator.c
	gcc 04_ConditionalOperator.o -o 04_ConditionalOperator

run:
	@./04_ConditionalOperator

clean:
	rm -rf 04_ConditionalOperator 04_ConditionalOperator.o 