01_ArithMeticOperator:01_ArithMeticOperator.c
	gcc -c 01_ArithMeticOperator.c
	gcc 01_ArithMeticOperator.o -o 01_ArithMeticOperator

run:
	@./01_ArithMeticOperator

clean:
	rm -rf 01_ArithMeticOperator 01_ArithMeticOperator.o