05_SizeOfPrimitiveDataTypes:05_SizeOfPrimitiveDataTypes.c
	gcc -c 05_SizeOfPrimitiveDataTypes.c
	gcc 05_SizeOfPrimitiveDataTypes.o -o 05_SizeOfPrimitiveDataTypes

run:
	@./05_SizeOfPrimitiveDataTypes

clean:
	rm -rf 05_SizeOfPrimitiveDataTypes 05_SizeOfPrimitiveDataTypes.o