02_AssignmentOperator:02_AssignmentOperator.c
	gcc -c 02_AssignmentOperator.c
	gcc 02_AssignmentOperator.o -o 02_AssignmentOperator

run:
	@./02_AssignmentOperator

clean:
	rm -rf 02_AssignmentOperator 02_AssignmentOperator.o